language: node_js
node_js:
  - "10"
cache:
  - npm
before_script:
  - npm ci
script: 
  - npm run lint
  - npm run test
  - npm run deploy
  - now alias --token=$ZEIT_KEY -V 2 node-labs-execution-$TRAVIS_BRANCH